# Generated by Django 4.0.5 on 2022-06-09 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('url', models.TextField()),
                ('summary', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=30)),
            ],
        ),
    ]
